version: '3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=youruser
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
    volumes:
      - ./n8n-data:/root/.n8n
    networks:
      - my_network
    restart: always

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - n8n
    restart: always

networks:
  my_network:
    external: true
